compute_environment: LOCAL_MACHINE

gpu_ids: "0,1,2,3,4,5,6,7"
num_processes: 8  # should be the same as the number of GPUs

debug: false
deepspeed_config:
  deepspeed_config_file: /home/zihao/CogVideo/finetune/configs/zero3.yaml  # e.g. configs/zero2.yaml, need use absolute path
  zero3_init_flag: true
distributed_type: DEEPSPEED
# fsdp_config:
#   fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
#   fsdp_backward_prefetch_policy: BACKWARD_PRE
#   fsdp_forward_prefetch: false
#   fsdp_cpu_ram_efficient_loading: true
#   fsdp_offload_params: false
#   fsdp_sharding_strategy: FULL_SHARD
#   fsdp_state_dict_type: SHARDED_STATE_DICT
#   fsdp_sync_module_states: true
#   fsdp_transformer_layer_cls_to_wrap: CogVideoXBlock
#   fsdp_use_orig_params: true
# distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
num_machines: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false